version: '3'

services:

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: go-server
    environment: 
      PORT: 50051
      DB_HOST: db
      DB_PASSWORD: passwd
      DB_USER: user
      DB_NAME: db
      DB_PORT: 5432

    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M
    depends_on: [db]
    networks: 
      - grpc-network

  go-client:
    build:
      context: .
      dockerfile: Dockerfile
      target: go-client
    environment: 
      HOST: go-server
      PORT: 50051
      API_PORT: 8888

    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 20M
    depends_on: [db]  
    ports: 
      - 8888:8888
    networks: 
      - grpc-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432      
    networks: 
      - grpc-network      

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: we@can.do.it
      PGADMIN_DEFAULT_PASSWORD: we
      PGADMIN_LISTEN_PORT: 80
    ports:
    - "8080:80"    
    networks: 
      - grpc-network     
 
networks: 
  grpc-network:
    driver: bridge