FROM golang:1.22 as client_builder

ENV GO111MODULE=on
ENV CGO_ENABLED=0

WORKDIR /app
COPY . .
RUN go build -o /client-app /app/cmd/client/main.go

FROM scratch as client

COPY --from=client_builder /client-app /svc

EXPOSE 8000
CMD ["/svc"]