apiVersion: v1
data:
  API_PORT: ODg4OA==
  ENVIRONMENT: bG9jYWw=
  GRPC_HOST: c2VydmVyLmdycGM=
  GRPC_PORT: NTAwNTM=
  LOG_LEVEL: ZGVidWc=
  LOG_SERVICENAME: OTBQT0VDTElFTlQ=
  SERVER_KEY: c29tZS1yYW5kb20ta2V5Yw==
kind: Secret
metadata:
  creationTimestamp: null
  name: client-secrets
  namespace: grpc
