// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: ports.proto

package portpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PortServiceClient is the client API for PortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortServiceClient interface {
	// Client Streaming
	Update(ctx context.Context, opts ...grpc.CallOption) (PortService_UpdateClient, error)
	// Server Streaming
	Retrieve(ctx context.Context, in *RetrievePortsRequest, opts ...grpc.CallOption) (PortService_RetrieveClient, error)
}

type portServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortServiceClient(cc grpc.ClientConnInterface) PortServiceClient {
	return &portServiceClient{cc}
}

func (c *portServiceClient) Update(ctx context.Context, opts ...grpc.CallOption) (PortService_UpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[0], "/port.PortService/Update", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceUpdateClient{stream}
	return x, nil
}

type PortService_UpdateClient interface {
	Send(*PortRequest) error
	CloseAndRecv() (*PortResponse, error)
	grpc.ClientStream
}

type portServiceUpdateClient struct {
	grpc.ClientStream
}

func (x *portServiceUpdateClient) Send(m *PortRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *portServiceUpdateClient) CloseAndRecv() (*PortResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PortResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *portServiceClient) Retrieve(ctx context.Context, in *RetrievePortsRequest, opts ...grpc.CallOption) (PortService_RetrieveClient, error) {
	stream, err := c.cc.NewStream(ctx, &PortService_ServiceDesc.Streams[1], "/port.PortService/Retrieve", opts...)
	if err != nil {
		return nil, err
	}
	x := &portServiceRetrieveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortService_RetrieveClient interface {
	Recv() (*RetrievePortsResponse, error)
	grpc.ClientStream
}

type portServiceRetrieveClient struct {
	grpc.ClientStream
}

func (x *portServiceRetrieveClient) Recv() (*RetrievePortsResponse, error) {
	m := new(RetrievePortsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PortServiceServer is the server API for PortService service.
// All implementations must embed UnimplementedPortServiceServer
// for forward compatibility
type PortServiceServer interface {
	// Client Streaming
	Update(PortService_UpdateServer) error
	// Server Streaming
	Retrieve(*RetrievePortsRequest, PortService_RetrieveServer) error
	mustEmbedUnimplementedPortServiceServer()
}

// UnimplementedPortServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPortServiceServer struct {
}

func (UnimplementedPortServiceServer) Update(PortService_UpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPortServiceServer) Retrieve(*RetrievePortsRequest, PortService_RetrieveServer) error {
	return status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedPortServiceServer) mustEmbedUnimplementedPortServiceServer() {}

// UnsafePortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortServiceServer will
// result in compilation errors.
type UnsafePortServiceServer interface {
	mustEmbedUnimplementedPortServiceServer()
}

func RegisterPortServiceServer(s grpc.ServiceRegistrar, srv PortServiceServer) {
	s.RegisterService(&PortService_ServiceDesc, srv)
}

func _PortService_Update_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PortServiceServer).Update(&portServiceUpdateServer{stream})
}

type PortService_UpdateServer interface {
	SendAndClose(*PortResponse) error
	Recv() (*PortRequest, error)
	grpc.ServerStream
}

type portServiceUpdateServer struct {
	grpc.ServerStream
}

func (x *portServiceUpdateServer) SendAndClose(m *PortResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *portServiceUpdateServer) Recv() (*PortRequest, error) {
	m := new(PortRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PortService_Retrieve_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RetrievePortsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortServiceServer).Retrieve(m, &portServiceRetrieveServer{stream})
}

type PortService_RetrieveServer interface {
	Send(*RetrievePortsResponse) error
	grpc.ServerStream
}

type portServiceRetrieveServer struct {
	grpc.ServerStream
}

func (x *portServiceRetrieveServer) Send(m *RetrievePortsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// PortService_ServiceDesc is the grpc.ServiceDesc for PortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "port.PortService",
	HandlerType: (*PortServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Update",
			Handler:       _PortService_Update_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Retrieve",
			Handler:       _PortService_Retrieve_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ports.proto",
}
