apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-client
  name: grpc-client
spec:
  type: NodePort
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: grpc-client
