apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
  namespace: grpc  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - image: eduardobcolombo/grpc-server:1.0
        name: grpc-server
        ports:
          - containerPort: 50053
        envFrom:
          - secretRef:
              name: server-secrets