apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: grpc  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: eduardobcolombo/server:1.0
        name: server
        ports:
          - containerPort: 50053
        envFrom:
          - secretRef:
              name: server-secrets