apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server
  name: grpc-server
spec:
  type: NodePort
  ports:
  - port: 50053
    protocol: TCP
    targetPort: 50053
  selector:
    app: grpc-server
